services:
  web:
    build:
      context: .
      target: builder
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/static
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

volumes:
  media_data:
  static_data:
