[phases.setup]
nixPkgs = ['python311', 'postgresql', 'gcc']

[phases.install]
cmds = ['python -m pip install --upgrade pip']

[phases.build]
cmds = ['pip install -r requirements.txt']

[start]
cmd = '/app/start.sh'
