# Generated by Django 5.1.3 on 2024-12-07 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person making contact', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(help_text='Email address for correspondence', max_length=254)),
                ('contact_reason', models.CharField(choices=[('other', 'Other'), ('buy_project', 'Buy a project that is for sale'), ('ecommerce', 'Bespoke eCommerce store'), ('lms', 'Bespoke Learning Management System'), ('speaking', 'Speaking/Training Opportunity')], default='other', help_text='Reason for making contact', max_length=20)),
                ('message', models.TextField(help_text='The message content (1000 characters max)', validators=[django.core.validators.MinLengthValidator(10, 'Message must be at least 10 characters long'), django.core.validators.MaxLengthValidator(1000, 'Message cannot exceed 1000 characters')])),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the sender', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied')], default='new', help_text='Current status of the contact message', max_length=20)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information', null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='contact_con_ip_addr_f44b25_idx'), models.Index(fields=['status'], name='contact_con_status_9a9384_idx')],
            },
        ),
    ]
