# Generated by Django 5.1.3 on 2024-11-10 18:11

import apps.portfolio.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime this object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The datetime this object was last updated')),
                ('meta_title', models.CharField(blank=True, help_text='Maximum 60 characters. Should be unique and descriptive.', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Maximum 160 characters. Provide a concise summary.', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords. Maximum 10 keywords.', max_length=255)),
                ('title', models.CharField(help_text='Title of the portfolio project', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('description', models.TextField(help_text='Detailed description of the project')),
                ('short_description', models.CharField(help_text='Brief summary of the project', max_length=200)),
                ('featured_image', models.ImageField(blank=True, help_text='Upload a JPG or PNG image', null=True, upload_to=apps.portfolio.models.portfolio_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('project_url', models.URLField(blank=True, help_text='Live project URL (if available)')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', validators=[apps.portfolio.models.validate_github_url])),
                ('is_featured', models.BooleanField(default=False, help_text='Display this project in featured sections')),
                ('order', models.IntegerField(default=0, help_text='Display order in the portfolio list')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime this object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The datetime this object was last updated')),
                ('name', models.CharField(help_text='Name of the technology (e.g., Python, React, Django)', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', unique=True)),
                ('icon', models.CharField(help_text='Icon identifier or URL for the technology', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime this object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The datetime this object was last updated')),
                ('image', models.ImageField(help_text='Additional project image (JPG or PNG)', upload_to=apps.portfolio.models.portfolio_gallery_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('caption', models.CharField(blank=True, help_text='Description of the image', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order in the gallery')),
                ('portfolio', models.ForeignKey(help_text='Portfolio project this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='technologies',
            field=models.ManyToManyField(help_text='Technologies used in this project', related_name='portfolios', to='portfolio.technology'),
        ),
    ]
