# Generated by Django 5.1.3 on 2024-11-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_status_technology_category'),
    ]

    operations = [
    ]
