# Generated by Django 5.1.3 on 2024-11-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20241121_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='live_site_url',
            field=models.URLField(blank=True, help_text='URL to the live deployed project', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='external_url_type',
            field=models.CharField(blank=True, choices=[('github', 'GitHub Repository'), ('marketplace', 'Marketplace Listing'), ('live', 'Visit Live Site')], max_length=20, null=True),
        ),
    ]
