# Generated by Django 5.1.3 on 2024-11-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_live_site_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='external_url_type',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True, help_text='URL to the GitHub repository for this project', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL to the external marketplace listing (e.g., Flippa)', null=True),
        ),
    ]
